<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>VAR.Toolbox.TestPlugin</RootNamespace>
    <AssemblyName>VAR.Toolbox.TestPlugin</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Notes.md" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VAR.Toolbox\VAR.Toolbox.csproj" />
  </ItemGroup>

</Project>
