<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>Toolbox.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\VAR.HttpServer\VAR.HttpServer\HttpProcessor.cs">
      <Link>Code\HttpServer\HttpProcessor.cs</Link>
    </Compile>
    <Compile Include="..\VAR.HttpServer\VAR.HttpServer\HttpServer.cs">
      <Link>Code\HttpServer\HttpServer.cs</Link>
    </Compile>
    <Compile Include="..\VAR.HttpServer\VAR.HttpServer\HttpUtility.cs">
      <Link>Code\HttpServer\HttpUtility.cs</Link>
    </Compile>
    <Compile Include="..\VAR.HttpServer\VAR.HttpServer\IHttpHandler.cs">
      <Link>Code\HttpServer\IHttpHandler.cs</Link>
    </Compile>
    <Compile Include="..\VAR.Json\VAR.Json\JsonParser.cs">
      <Link>Code\Json\JsonParser.cs</Link>
    </Compile>
    <Compile Include="..\VAR.Json\VAR.Json\JsonWriter.cs">
      <Link>Code\Json\JsonWriter.cs</Link>
    </Compile>
    <Compile Include="..\VAR.Json\VAR.Json\ObjectActivator.cs">
      <Link>Code\Json\ObjectActivator.cs</Link>
    </Compile>
    <Compile Include="..\VAR.Json\VAR.Json\ParserContext.cs">
      <Link>Code\Json\ParserContext.cs</Link>
    </Compile>
    <Compile Update="Controls\CButton.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\CComboBox.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\CDateTimePicker.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\CGroupBox.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\CSplitContainer.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\CtrImageViewer.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\CtrOutput.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\ListBoxMonospace.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\ListBoxNormal.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\SubFrame.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\TextBoxMonospace.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\TextBoxNormal.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="UI\Tools\PnlActivity.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UI\Tools\PnlCover.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UI\Tools\PnlSuspension.cs">
      <SubType>UserControl</SubType>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Images\Toolbox.png" />
    <Content Include="Images\toolbox.svg" />
    <Content Include="Toolbox.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.1.0-preview1.26124.5" />
    <PackageReference Include="System.Drawing.Common" Version="11.0.0-preview.3.26207.106" />
  </ItemGroup>
</Project>